### ISSUE TITLE
模块设置为1时，总是提示内存不足

### ISSUE THREAD

**Issue by WalkingwithAI** [lldacing/ComfyUI_BiRefNet_ll#3]
您好，模块设置为1时，总是提示内存不足。有时清理多余内存后，到了模型处理部分后，又会提示内存不足。

**Comment by lldacing** [comment]
> 您好，模块设置为1时，总是提示内存不足。有时清理多余内存后，到了模型处理部分后，又会提示内存不足。

显存不足吧，你机器多大显存

**Comment by WalkingwithAI** [comment]
> > 您好，模块设置为1时，总是提示内存不足。有时清理多余内存后，到了模型处理部分后，又会提示内存不足。
> 
> 显存不足吧，你机器多大显存

8G显存，但是我看显存其实没有占满，大概在5G左右，反倒是内存一直是99%，我还加了很多虚拟内存，还是占满的。麻烦大佬有空看下。

!!! Exception during processing !!! Unable to allocate 23.7 MiB for an array with shape (1920, 1080, 3) and data type float32
Traceback (most recent call last):
  File "G:\ComfyUI_Portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_Portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_Portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\ComfyUI_Portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_Portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnetNode.py", line 184, in rem_bg
    pil_image = tensor_to_pil(image)
                ^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_Portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\util.py", line 7, in tensor_to_pil
    return Image.fromarray(np.clip(255. * image.cpu().numpy().squeeze(), 0, 255).astype(np.uint8))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_Portable\python_embeded\Lib\site-packages\numpy\core\fromnumeric.py", line 2169, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_Portable\python_embeded\Lib\site-packages\numpy\core\fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_Portable\python_embeded\Lib\site-packages\numpy\core\_methods.py", line 99, in _clip
    return um.clip(a, min, max, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 23.7 MiB for an array with shape (1920, 1080, 3) and data type float32

**Comment by lldacing** [comment]
> > > 您好，模块设置为1时，总是提示内存不足。有时清理多余内存后，到了模型处理部分后，又会提示内存不足。
> > 
> > 
> > 显存不足吧，你机器多大显存
> 
> 8G显存，但是我看显存其实没有占满，大概在5G左右，反倒是内存一直是99%，我还加了很多虚拟内存，还是占满的。麻烦大佬有空看下。
> 
> !!! Exception during processing !!! Unable to allocate 23.7 MiB for an array with shape (1920, 1080, 3) and data type float32 Traceback (most recent call last): File "G:\ComfyUI_Portable\ComfyUI\execution.py", line 317, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\ComfyUI\execution.py", line 192, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\ComfyUI\execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i) File "G:\ComfyUI_Portable\ComfyUI\execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnetNode.py", line 184, in rem_bg pil_image = tensor_to_pil(image) ^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\util.py", line 7, in tensor_to_pil return Image.fromarray(np.clip(255. * image.cpu().numpy().squeeze(), 0, 255).astype(np.uint8)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\python_embeded\Lib\site-packages\numpy\core\fromnumeric.py", line 2169, in clip return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\python_embeded\Lib\site-packages\numpy\core\fromnumeric.py", line 59, in _wrapfunc return bound(*args, **kwds) ^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\python_embeded\Lib\site-packages\numpy\core_methods.py", line 99, in _clip return um.clip(a, min, max, out=out, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ numpy.core._exceptions._ArrayMemoryError: Unable to allocate 23.7 MiB for an array with shape (1920, 1080, 3) and data type float32

是你图片太大了，你可以在图片节点后面加一个缩小图片的节点再抠图

**Comment by WalkingwithAI** [comment]
> > > > 您好，模块设置为1时，总是提示内存不足。有时清理多余内存后，到了模型处理部分后，又会提示内存不足。
> > > 
> > > 
> > > 显存不足吧，你机器多大显存
> > 
> > 
> > 8G显存，但是我看显存其实没有占满，大概在5G左右，反倒是内存一直是99%，我还加了很多虚拟内存，还是占满的。麻烦大佬有空看下。
> > !!! Exception during processing !!! Unable to allocate 23.7 MiB for an array with shape (1920, 1080, 3) and data type float32 Traceback (most recent call last): File "G:\ComfyUI_Portable\ComfyUI\execution.py", line 317, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\ComfyUI\execution.py", line 192, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\ComfyUI\execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i) File "G:\ComfyUI_Portable\ComfyUI\execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnetNode.py", line 184, in rem_bg pil_image = tensor_to_pil(image) ^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\util.py", line 7, in tensor_to_pil return Image.fromarray(np.clip(255. * image.cpu().numpy().squeeze(), 0, 255).astype(np.uint8)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\python_embeded\Lib\site-packages\numpy\core\fromnumeric.py", line 2169, in clip return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\python_embeded\Lib\site-packages\numpy\core\fromnumeric.py", line 59, in _wrapfunc return bound(*args, **kwds) ^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\python_embeded\Lib\site-packages\numpy\core_methods.py", line 99, in _clip return um.clip(a, min, max, out=out, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ numpy.core._exceptions._ArrayMemoryError: Unable to allocate 23.7 MiB for an array with shape (1920, 1080, 3) and data type float32
> 
> 是你图片太大了，抠图之前会先转换图片数据格式，这一步内存不足了，你可以在图片节点后面加一个缩小图片的节点再抠图

大佬，方便加微信聊下吗？可以有偿

**Comment by lldacing** [comment]
> > > > > 您好，模块设置为1时，总是提示内存不足。有时清理多余内存后，到了模型处理部分后，又会提示内存不足。
> > > > 
> > > > 
> > > > 显存不足吧，你机器多大显存
> > > 
> > > 
> > > 8G显存，但是我看显存其实没有占满，大概在5G左右，反倒是内存一直是99%，我还加了很多虚拟内存，还是占满的。麻烦大佬有空看下。
> > > !!! Exception during processing !!! Unable to allocate 23.7 MiB for an array with shape (1920, 1080, 3) and data type float32 Traceback (most recent call last): File "G:\ComfyUI_Portable\ComfyUI\execution.py", line 317, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\ComfyUI\execution.py", line 192, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\ComfyUI\execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i) File "G:\ComfyUI_Portable\ComfyUI\execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnetNode.py", line 184, in rem_bg pil_image = tensor_to_pil(image) ^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\util.py", line 7, in tensor_to_pil return Image.fromarray(np.clip(255. * image.cpu().numpy().squeeze(), 0, 255).astype(np.uint8)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\python_embeded\Lib\site-packages\numpy\core\fromnumeric.py", line 2169, in clip return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\python_embeded\Lib\site-packages\numpy\core\fromnumeric.py", line 59, in _wrapfunc return bound(*args, **kwds) ^^^^^^^^^^^^^^^^^^^^ File "G:\ComfyUI_Portable\python_embeded\Lib\site-packages\numpy\core_methods.py", line 99, in _clip return um.clip(a, min, max, out=out, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ numpy.core._exceptions._ArrayMemoryError: Unable to allocate 23.7 MiB for an array with shape (1920, 1080, 3) and data type float32
> > 
> > 
> > 是你图片太大了，抠图之前会先转换图片数据格式，这一步内存不足了，你可以在图片节点后面加一个缩小图片的节点再抠图
> 
> 大佬，方便加微信聊下吗？可以有偿

可以加QQ：112083512@qq.com

**Comment by WalkingwithAI** [comment]
> 112083512

OK，加您了

**Comment by lldacing** [comment]
> > 112083512
> 
> OK，加您了

不好意思，写错了，少写了一位：1120838512
