### ISSUE TITLE
运行报错，模型已下载

### ISSUE THREAD

**Issue by Andy2024mm** [lldacing/ComfyUI_BiRefNet_ll#6]
<img width="1052" alt="PixPin_2024-10-20_23-00-57" src="https://github.com/user-attachments/assets/f249b4c8-5bf9-4788-8d5c-f41427111b4c">

**Comment by lldacing** [comment]
在什么机器上运行的，用的那个加载模型的节点

**Comment by Andy2024mm** [comment]
已解决，是torch版本过高，降回2.4即可，谢谢！

**Comment by lldacing** [comment]
> 已解决，是torch版本过高，降回2.4即可，谢谢！

有问题的是哪个版本，我这边用torch2.4.1+cu124和torchvision 0.19.1+cu124没有问题

**Comment by lldacing** [comment]
测试了torch2.5.0和2.5.1均无问题
