### ISSUE TITLE
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

### ISSUE THREAD

**Issue by TheWingAg90** [lldacing/ComfyUI_BiRefNet_ll#7]
![image](https://github.com/user-attachments/assets/60950987-0cb7-42cd-adf7-ec9e2cdf2e72)
![image](https://github.com/user-attachments/assets/ecdafb71-a4b6-4568-92e9-752e14b61619)

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnetNode.py", line 104, in load_model
    download_birefnet_model(model_name)
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnetNode.py", line 59, in download_birefnet_model
    download_models(model_root, model_urls)
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnetNode.py", line 47, in download_models
    download_url_to_file(url, dst=local_path)
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\hub.py", line 622, in download_url_to_file
    u = urlopen(req)
        ^^^^^^^^^^^^
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
help me. thanks

**Comment by lldacing** [comment]
> ![image](https://private-user-images.githubusercontent.com/157227635/379423874-60950987-0cb7-42cd-adf7-ec9e2cdf2e72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NDIzMzAsIm5iZiI6MTcyOTc0MjAzMCwicGF0aCI6Ii8xNTcyMjc2MzUvMzc5NDIzODc0LTYwOTUwOTg3LTBjYjctNDJjZC1hZGY3LWVjOWUyY2RmMmU3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwMzUzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzdmYjg3M2FlM2Y4ZWRmOWYwYTliOTJkNDRmMzZjMDI1ZTk2NDU3MmM4MTBlODQ4MjE4M2RjNzQ2MTE5YzFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HKZPXf5bs8tpvv64d-ZNpT-cmPFO81UNaPcEQHZSTGs) ![image](https://private-user-images.githubusercontent.com/157227635/379424314-ecdafb71-a4b6-4568-92e9-752e14b61619.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NDIzMzAsIm5iZiI6MTcyOTc0MjAzMCwicGF0aCI6Ii8xNTcyMjc2MzUvMzc5NDI0MzE0LWVjZGFmYjcxLWE0YjYtNDU2OC05MmU5LTc1MmUxNGI2MTYxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwMzUzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGJiNGI0YjczY2EwYmU5Njc3MWM0YmVhN2QwNWFhOTk2ZTU5YTNlMmY1NTQyZDc1ODAzZDc1NWZlYjUxNTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.I0ttxPqyShUu3ZyZ45Ml7VErS5LfYz3X6Ijl5XBotnw)
> 
> During handling of the above exception, another exception occurred: Traceback (most recent call last): File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i) File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnetNode.py", line 104, in load_model download_birefnet_model(model_name) File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnetNode.py", line 59, in download_birefnet_model download_models(model_root, model_urls) File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnetNode.py", line 47, in download_models download_url_to_file(url, dst=local_path) File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\hub.py", line 622, in download_url_to_file u = urlopen(req) ^^^^^^^^^^^^ File "urllib\request.py", line 216, in urlopen File "urllib\request.py", line 519, in open File "urllib\request.py", line 536, in _open File "urllib\request.py", line 496, in _call_chain File "urllib\request.py", line 1391, in https_open File "urllib\request.py", line 1351, in do_open urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)> help me. thanks

I think this may be a network problem. You can download the model and put it in the models/BirefNet directory according to the readme document , then use the LoadRembgByBiRefNetModel node to load the model.

**Comment by TheWingAg90** [comment]
> > ![image](https://private-user-images.githubusercontent.com/157227635/379423874-60950987-0cb7-42cd-adf7-ec9e2cdf2e72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NDIzMzAsIm5iZiI6MTcyOTc0MjAzMCwicGF0aCI6Ii8xNTcyMjc2MzUvMzc5NDIzODc0LTYwOTUwOTg3LTBjYjctNDJjZC1hZGY3LWVjOWUyY2RmMmU3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwMzUzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzdmYjg3M2FlM2Y4ZWRmOWYwYTliOTJkNDRmMzZjMDI1ZTk2NDU3MmM4MTBlODQ4MjE4M2RjNzQ2MTE5YzFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HKZPXf5bs8tpvv64d-ZNpT-cmPFO81UNaPcEQHZSTGs) ![image](https://private-user-images.githubusercontent.com/157227635/379424314-ecdafb71-a4b6-4568-92e9-752e14b61619.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NDIzMzAsIm5iZiI6MTcyOTc0MjAzMCwicGF0aCI6Ii8xNTcyMjc2MzUvMzc5NDI0MzE0LWVjZGFmYjcxLWE0YjYtNDU2OC05MmU5LTc1MmUxNGI2MTYxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNFQwMzUzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGJiNGI0YjczY2EwYmU5Njc3MWM0YmVhN2QwNWFhOTk2ZTU5YTNlMmY1NTQyZDc1ODAzZDc1NWZlYjUxNTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.I0ttxPqyShUu3ZyZ45Ml7VErS5LfYz3X6Ijl5XBotnw)
> > During handling of the above exception, another exception occurred: Traceback (most recent call last): File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i) File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnetNode.py", line 104, in load_model download_birefnet_model(model_name) File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnetNode.py", line 59, in download_birefnet_model download_models(model_root, model_urls) File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_BiRefNet_ll\birefnetNode.py", line 47, in download_models download_url_to_file(url, dst=local_path) File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\hub.py", line 622, in download_url_to_file u = urlopen(req) ^^^^^^^^^^^^ File "urllib\request.py", line 216, in urlopen File "urllib\request.py", line 519, in open File "urllib\request.py", line 536, in _open File "urllib\request.py", line 496, in _call_chain File "urllib\request.py", line 1391, in https_open File "urllib\request.py", line 1351, in do_open urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)> help me. thanks
> 
> I think this may be a network problem. You can download the model and put it in the models/BirefNet directory according to the readme document , then use the LoadRembgByBiRefNetModel node to load the model.

i think my win is not active. i can downloaded model "ComfyUI_BiRefNet_ll" and put it's in comfyui/models/BirefNet. and done. thanks for helping.
note: ComfyUI_BiRefNet_ll # ComfyUI_BiRefNet. but model of ComfyUI_BiRefNet_ll and ComfyUI_BiRefNet in ...comfyui/models/BirefNet
